apiVersion: v2
name: reetwiz-fellowblogs-chart
description: A Helm chart for the FellowBlogs 3-tier application with a Primary/Replica PostgreSQL cluster.
type: application
version: 0.1.0
appVersion: "1.0.0"
