imagePullSecrets:
  enabled: true
  name: "fellowblogs-ecr-secret"

postgres:
  name: postgres
  replicaCount: 3
  image:
    repository: "docker.io/bitnami/postgresql"
    tag: "17.5.0-debian-12-r20"
    pullPolicy: "IfNotPresent"
  service:
    primary: { port: 5432 }
    replica: { port: 5432 }
  dbName: ""
  dbUser: ""
  dbPassword: ""
  storage:
    size: 2Gi
    storageClassName: "local-path"

frontend:
  name: frontend
  replicaCount: 2
  image: { repository: "702865854817.dkr.ecr.us-east-1.amazonaws.com/reetwiz-frontend", tag: "latest", pullPolicy: "Always" }
  service: { port: 80 }

backend1:
  name: backend1
  replicaCount: 2
  image: { repository: "702865854817.dkr.ecr.us-east-1.amazonaws.com/reetwiz-backend1", tag: "latest", pullPolicy: "Always" }
  service: { port: 3000 }

backend2:
  name: backend2
  replicaCount: 2
  image: { repository: "702865854817.dkr.ecr.us-east-1.amazonaws.com/reetwiz-backend2", tag: "latest", pullPolicy: "Always" }
  service: { port: 3001 }

secrets:
  clerkSecretKey: ""
config:
  dbClient: "pg"
  nodeEnv: "local"
  clerkPublishableKey: ""

probes:
  enabled: true
  healthPath: "/api/health"
  liveness: { initialDelaySeconds: 20, periodSeconds: 20 }
  readiness: { initialDelaySeconds: 10, periodSeconds: 10 }

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPU: 80

ingress:
  enabled: false
  className: "nginx"
  host: "fellowblogs.reetwiz.local"
  tls:
    enabled: false
    secretName: "fellowblogs-tls-secret"
