apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "reetwiz-fellowblogs-chart.fullname" . }}-{{ .Values.frontend.name }}
  labels:
    {{- include "reetwiz-fellowblogs-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "reetwiz-fellowblogs-chart.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ .Values.frontend.name }}
  template:
    metadata:
      labels:
        {{- include "reetwiz-fellowblogs-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: {{ .Values.frontend.name }}
    spec:
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecrets.name }}
      {{- end }}
      containers:
      - name: {{ .Values.frontend.name }}
        image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.frontend.service.port }}
        envFrom:
        - configMapRef: { name: {{ include "reetwiz-fellowblogs-chart.fullname" . }}-config }
        {{- if .Values.probes.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.frontend.service.port }}
          initialDelaySeconds: 20
          periodSeconds: 10
        {{- end }}